// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGoihTsbHWm8o2Op6PrKPogeRGYp6csG8',
    appId: '1:213980855279:web:e7e1cb1796b49992f4141a',
    messagingSenderId: '213980855279',
    projectId: 'utilitymeter-3feed',
    authDomain: 'utilitymeter-3feed.firebaseapp.com',
    storageBucket: 'utilitymeter-3feed.firebasestorage.app',
    measurementId: 'G-LJ7R6LM0YZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjRvuY1GGsr9MnFvtgleR46FBuHZwj3uE',
    appId: '1:213980855279:android:86418101c3459855f4141a',
    messagingSenderId: '213980855279',
    projectId: 'utilitymeter-3feed',
    storageBucket: 'utilitymeter-3feed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0bKA2vsysjlNUTCAUvIHnwUcvzvqnJpk',
    appId: '1:213980855279:ios:89f0c41f8e7f96b8f4141a',
    messagingSenderId: '213980855279',
    projectId: 'utilitymeter-3feed',
    storageBucket: 'utilitymeter-3feed.firebasestorage.app',
    iosBundleId: 'com.example.utilityMeter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0bKA2vsysjlNUTCAUvIHnwUcvzvqnJpk',
    appId: '1:213980855279:ios:89f0c41f8e7f96b8f4141a',
    messagingSenderId: '213980855279',
    projectId: 'utilitymeter-3feed',
    storageBucket: 'utilitymeter-3feed.firebasestorage.app',
    iosBundleId: 'com.example.utilityMeter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGoihTsbHWm8o2Op6PrKPogeRGYp6csG8',
    appId: '1:213980855279:web:1857b86c7e309d14f4141a',
    messagingSenderId: '213980855279',
    projectId: 'utilitymeter-3feed',
    authDomain: 'utilitymeter-3feed.firebaseapp.com',
    storageBucket: 'utilitymeter-3feed.firebasestorage.app',
    measurementId: 'G-S58HCZCJYX',
  );
}
